version: '3'

services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=masadamsahid
      - MONGO_PASSWORD=passwordqu
    command: npm run dev
    
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=masadamsahid
      - MONGO_INITDB_ROOT_PASSWORD=passwordqu

